zeppelin:
  build: .
  environment:
    ZEPPELIN_PORT: 8080
  ports:
    - 8080:8080
    - 8081:8081
    - 4040:4040
  volumes:
    - ./notebooks:/usr/zeppelin/notebook
    - ./configs:/tmp/configs
    - ./data:/tmp/data
